##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Create a makefil that compile your lib
##

to_compile:
	gcc -c *.c
	ar rc libmy.a *.o
	cp libmy.a ../

clean:
	rm -rf *.o
	rm -rf *~
	rm -rf "#*#"
